### ISSUE TITLE
sorry i dont understand how this works

### ISSUE THREAD

**Issue by hoekiesda** [OXIDprojects/Google-Base-Export#2]
one of these applies:

1) incomplete doc, or
2) incomplete code.

Because it is not doing anything. It provides an empty export over and over again. BTW why is there no superclass implementation? I figured out how the classes work, i guess... But still no export :(

**Comment by kermie** [comment]
Did you see this comment in README?
"Originally registered on 2010-04-09 by Frank Schuhmacher on former OXIDprojects."

I guess the module was made for an older version of OXID eShop and has to be adapted (get rid of outdated methods etc.)

**Comment by hoekiesda** [comment]
Sure i read that, and also saw the last commit was only 2 months ago... I'll have a look at it and try to fix it.

**Comment by kermie** [comment]
The last commit was the initial commit when moving from projects.oxidforge.org to GitHub. No changes made to the code at this moment. Thanks for fixing :+1:
